[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_USE_LOG=1
    -D VOXA_VERSION=\"1.0.0\"

lib_deps =
    lvgl/lvgl@^9.2.2
    lovyan03/LovyanGFX@^1.2.0